spring:
  application:
    name: map-tms
  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true
  mvc:
    static-path-pattern: /**
  servlet:
    multipart:
      max-file-size: 5000MB
      max-request-size: 5000MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: dm.jdbc.driver.DmDriver
    #数据库地址,端口号,模式名根据实际开发环境填写
    #    url: jdbc:dm://127.0.0.1:5236?schema=HUADU
    url: jdbc:dm://localhost:5236?schema=cim
    #数据库的使用用户
    username: SYSDBA
    #实际使用数据库的密码
    password: SYSDBA
server:
  port: 8083


#Mybatis-plus配置
mybatis-plus:
  basePackage: com.map.mapper
  mapper-locations: classpath*:/mappings/**/*Mapper.xml
  typeAliasesPackage: com.map.po
  global-config:
    banner: false
    id-type: 4
    #字段策略 0:"忽略判断"- 1:"非 NULL 判断")- 2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    logic-delete-value: -1
    logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    log-impl:  org.apache.ibatis.logging.stdout.StdOutImpl

# 基础路径
#TILES_BASE_DIR: "D:\\"
TILES_BASE_DIR: "/Users/xushi/tiles/"
# 图片类型
IMAGE_TYPE: ".png"

# =============================================================================
# TerraForge API 配置 (TerraForge API Configuration)
# =============================================================================
terraforge:
  api:
    # 系统状态相关 API
    health-url: http://localhost:8000/api/health
    system-info-url: http://localhost:8000/api/system/info

    # 数据源管理相关 API
    datasources-url: http://localhost:8000/api/dataSources
    datasources-info-url: http://localhost:8000/api/dataSources/info

    # 结果浏览相关 API
    results-url: http://localhost:8000/api/results

    # 切片服务相关 API
    terrain-tile-url: http://localhost:8000/api/tile/terrain

    # 任务管理相关 API
    tasks-url: http://localhost:8000/api/tasks
    task-stop-url: http://localhost:8000/api/tasks/{taskId}/stop
    task-delete-url: http://localhost:8000/api/tasks/{taskId}
    task-cleanup-url: http://localhost:8000/api/tasks/cleanup

    # 辅助工具相关 API
    terrain-layer-url: http://localhost:8000/api/terrain/layer
    terrain-decompress-url: http://localhost:8000/api/terrain/decompress

    # 工作空间管理相关 API
    workspace-create-folder-url: http://localhost:8000/api/workspace/createFolder
    workspace-folder-url: http://localhost:8000/api/workspace/folder
    workspace-file-url: http://localhost:8000/api/workspace/file
    workspace-move-url: http://localhost:8000/api/workspace/move
    workspace-info-url: http://localhost:8000/api/workspace/info

    # 索引瓦片切片相关 API
    indexed-tiles-url: http://localhost:8000/api/tile/indexedTiles

    # 透明瓦片处理相关 API
    tiles-nodata-scan-url: http://localhost:8000/api/tiles/nodata/scan
    tiles-nodata-delete-url: http://localhost:8000/api/tiles/nodata/delete

    # 瓦片格式转换相关 API
    tile-convert-url: http://localhost:8000/api/tile/convert

    # 分析工具相关 API

    config-recommend-url: http://localhost:8000/api/config/recommend
    routes-url: http://localhost:8000/api/routes
    container-update-url: http://localhost:8000/api/container/update
