package com.terrain.common;

public enum CameraDirectionType {
    CAMERA_DIRECTION_UNKNOWN, CAMERA_DIRECTION_XPOS, CAMERA_DIRECTION_XNEG, CAMERA_DIRECTION_ZPOS, CAMERA_DIRECTION_ZNEG, CAMERA_DIRECTION_YPOS, CAMERA_DIRECTION_YNEG, CAMERA_DIRECTION_XPOS_ZNEG, CAMERA_DIRECTION_XNEG_ZNEG, CAMERA_DIRECTION_XNEG_ZPOS, CAMERA_DIRECTION_XPOS_ZPOS, CAMERA_DIRECTION_YPOS_ZNEG, CAMERA_DIRECTION_YPOS_ZPOS, CAMERA_DIRECTION_YNEG_ZNEG, CAMERA_DIRECTION_YNEG_ZPOS;

}
